sudo: required
services:
  - docker

before_install:
  - docker build -t samikmalhotra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samikmalhotra/react-test npm test -- --coverage

after_success:
  - docker build -t samikmalhotra/multi-client ./client
  - docker build -t samikmalhotra/multi-nginx ./nginx
  - docker build -t samikmalhotra/multi-server ./server
  - docker build -t samikmalhotra/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push samikmalhotra/multi-client
  - docker push samikmalhotra/multi-nginx
  - docker push samikmalhotra/multi-server
  - docker push samikmalhotra/multi-worker

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-772049835561"
  bucket_path: docker-multi
  on:
    branch: master

after_deploy: "echo 'done'"