sudo: required
services:
  - docker

before_install:
  - docker build -t samikmalhotra/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run samikmalhotra/react-test npm test -- --coverage

after_success:
  - docker build -t samikmalhotra/multi-client ./client
  - docker build -t samikmalhotra/multi-nginx ./nginx
  - docker build -t samikmalhotra/multi-server ./server
  - docker build -t samikmalhotra/multi-worker ./worker
  #login to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push to docker hub
  - docker push samikmalhotra/multi-client
  - docker push samikmalhotra/multi-nginx
  - docker push samikmalhotra/multi-server
  - docker push samikmalhotra/multi-worker